/*
 * dashboard.jsx(대시보드 원본 소스) 안에서 "순수 데이터 로직"(엑셀 파싱 + 병합 + 기본데이터)
 * 부분만 잘라내어 scripts/dataEngine.mjs 로 만들어주는 스크립트.
 *
 * 매번 자동화가 돌 때마다 dashboard.jsx의 DEFAULT_DATA는 최신 값으로 바뀌므로, 줄 번호가 아니라
 * 텍스트 마커를 기준으로 추출한다 — dashboard.jsx가 구조(섹션 순서/구분 주석)만 유지하면
 * DEFAULT_DATA 내용이 아무리 커져도 항상 정상적으로 추출됨.
 *
 * 사용법: node scripts/extract-engine.js [dashboard.jsx 경로] [출력 경로]
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const srcPath = process.argv[2] || path.join(__dirname, "..", "dashboard.jsx");
const outPath = process.argv[3] || path.join(__dirname, "dataEngine.mjs");

const src = fs.readFileSync(srcPath, "utf-8");
const lines = src.split("\n");

function findLineIndex(re, fromLine = 0) {
  for (let i = fromLine; i < lines.length; i++) {
    if (re.test(lines[i])) return i;
  }
  throw new Error(`extract-engine: 패턴을 찾지 못했습니다: ${re}`);
}

// 중첩된 "};" 를 건너뛰고, 들여쓰기 없는(줄 맨 앞) "};" 로 최상위 블록의 끝을 찾음
function findTopLevelClose(fromLine) {
  for (let i = fromLine; i < lines.length; i++) {
    if (/^\};\s*$/.test(lines[i])) return i;
  }
  throw new Error(`extract-engine: 최상위 블록의 닫는 "};" 를 찾지 못했습니다 (from line ${fromLine + 1})`);
}

function grabLines(a, b) {
  // a,b: 0-indexed, inclusive
  return lines.slice(a, b + 1).join("\n");
}

// 1) COLORS
const colorsStart = findLineIndex(/^const COLORS = \{/);
const colorsEnd = findTopLevelClose(colorsStart);
const colors = grabLines(colorsStart, colorsEnd);

// 2) CHANNEL_META ~ QUARTER_LABELS (짧은 상수 묶음, CHANNEL_META 시작부터 QUARTER_LABELS 줄까지)
const channelMetaStart = findLineIndex(/^const CHANNEL_META = \{/);
const quarterLabelsLine = findLineIndex(/^const QUARTER_LABELS = /, channelMetaStart + 1);
const channelMeta = grabLines(channelMetaStart, quarterLabelsLine);

// 3) DEFAULT_DATA
const defaultDataStart = findLineIndex(/^const DEFAULT_DATA = \{/);
const defaultDataEnd = findTopLevelClose(defaultDataStart + 1);
const defaultData = grabLines(defaultDataStart, defaultDataEnd);

// 4) excel parsing engine 섹션 (주석부터 mergeWithDefaults 끝까지, "export default function Dashboard()" 직전)
const engineStart = findLineIndex(/excel parsing engine/);
const componentStart = findLineIndex(/^export default function Dashboard\(\)/, engineStart + 1);
// componentStart 바로 앞 줄까지 (mergeWithDefaults의 닫는 "}"와 빈 줄들)
const engine = grabLines(engineStart, componentStart - 1);

// Node 환경 패치: FileReader(브라우저 전용) 대신 이미 메모리에 있는 Buffer를 그대로 사용
const patchedEngine = engine.replace(
  /function readFileAsArrayBuffer\(file\) \{[\s\S]*?\n\}/,
  `function readFileAsArrayBuffer(file) {
  // Node 환경: file 은 { name, buffer(Buffer) } 형태의 객체
  return Promise.resolve(file.buffer);
}`
);

const header = `/* =====================================================================
 * AUTO-GENERATED by scripts/extract-engine.js from dashboard.jsx — 직접 수정하지 마세요.
 * dashboard.jsx가 바뀔 때마다(자동화 실행 시) 이 파일도 다시 생성됩니다.
 * 대시보드 원본과 동일한 "엑셀 파싱 + 데이터 병합" 로직만 순수 함수로 뽑아낸 것입니다.
 * ===================================================================== */
import * as XLSX from "xlsx";

`;

const footer = `
// 새 판매채널이 새로 감지됐을 때 배정할 색상 팔레트
// (대시보드 원본에는 EXTRA_CHANNEL_COLORS 정의가 누락되어 있어 여기서 보강함 — 대시보드 쪽도 별도로 고쳐야 함)
const EXTRA_CHANNEL_COLORS = [COLORS.plum, "#8AA0A8", "#B4623E", "#5B7A9C", "#9C8A3E"];

export {
  DEFAULT_DATA, CHANNEL_KEYS, CHANNEL_META, REVENUE_KEYS, GIFTSHOP_KEYS,
  YEAR_FIELD_KEYS, EXTRA_CHANNEL_COLORS,
  processExcelFiles, mergeWithDefaults, mergeMonthlySeries, mergeMonthlyByKeyMap,
  mergeVendorMonthlyDetail, extractYearFields, normalizeCustomOrder, normalizeMarketEvent,
};
`;

const out = header + colors + "\n" + channelMeta + "\n" + defaultData + "\n" + patchedEngine + footer;
fs.writeFileSync(outPath, out, "utf-8");
console.log(`✓ ${outPath} 생성 완료 (${out.split("\n").length}줄)`);
